<InternetError>:
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        Label:
            text: "Erreur Internet"
            font_size: self.width*10/100
            color: utils.get_color_from_hex('#FFFFFF')
        Label:
            text: "Verifier votre connexion et relancer"
            font_size: self.width*5/100
            color: utils.get_color_from_hex('#FFFFFF')